### ISSUE TITLE
(question/comment) HystrixCommand instead of HystrixObervableCommand ?

### ISSUE THREAD

**Issue by bquenin** [ratpack/example-books#17]
Hi,

According to this thread https://github.com/Netflix/Hystrix/issues/805 and for my own understanding, wouldn't it be more adequate to rely on HystrixCommands (instead of HystrixObservableCommands) in BookDbCommands, therefore leveraging the thread isolation from Hystrix (instead of using Ratpack execControl) since all commands are blocking?

I'm not sure I'm clear, but I'd like to have your insights on this!

Thanks,
BQ.

**Comment by danveloper** [comment]
Hi @bquenin great question, thanks for asking!

We want to ensure that the blocking commands are scheduled using Ratpack's execution model so that the request lifecycle is properly maintained. Additionally, Ratpack takes extra measures to ensure that resources are utilized very effectively, so introducing another thread pool into the mix will only cause contention.

For RxJava (which Hystrix uses), Ratpack provides a scheduler, allowing observables to use the execution. This means that the steps taking prior to and after the `blocking` calls are made on the execution's computation thread pool, giving the most efficient resource utilization.

**Comment by bquenin** [comment]
ok, thanks for the clarification. I wasn't sure if both were equivalent or not.
I'll mimic your example then :)

**Comment by rhart** [comment]
This looks like it can be closed.  Please re-open if not
